// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Y3EL-xnYbDM38EkUOOASAUa6m8D0yUo',
    appId: '1:881858326553:web:88343f9002e4e9fd82ba88',
    messagingSenderId: '881858326553',
    projectId: 'fhirov',
    authDomain: 'fhirov.firebaseapp.com',
    databaseURL: 'https://fhirov-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fhirov.appspot.com',
    measurementId: 'G-9WTSW9LPQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ExexO5QaBBot86Aidvw9c5_2GxCMBrI',
    appId: '1:881858326553:android:a65b5f9e5940564682ba88',
    messagingSenderId: '881858326553',
    projectId: 'fhirov',
    databaseURL: 'https://fhirov-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fhirov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_nDRUM7VgngoWsQvCqSKsnJp_NyJXGog',
    appId: '1:881858326553:ios:3dbbf017df8c7eda82ba88',
    messagingSenderId: '881858326553',
    projectId: 'fhirov',
    databaseURL: 'https://fhirov-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fhirov.appspot.com',
    androidClientId: '881858326553-o81v6hrna3t6lumfmb52s27pnol96l0c.apps.googleusercontent.com',
    iosClientId: '881858326553-d2ajrrjp4fiv98ulffq6cssfuk2r8n88.apps.googleusercontent.com',
    iosBundleId: 'com.example.fhirpat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_nDRUM7VgngoWsQvCqSKsnJp_NyJXGog',
    appId: '1:881858326553:ios:3dbbf017df8c7eda82ba88',
    messagingSenderId: '881858326553',
    projectId: 'fhirov',
    databaseURL: 'https://fhirov-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fhirov.appspot.com',
    androidClientId: '881858326553-o81v6hrna3t6lumfmb52s27pnol96l0c.apps.googleusercontent.com',
    iosClientId: '881858326553-d2ajrrjp4fiv98ulffq6cssfuk2r8n88.apps.googleusercontent.com',
    iosBundleId: 'com.example.fhirpat',
  );
}
